# Generated by Django 5.0.7 on 2025-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(max_length=2000),
        ),
    ]
